# Generated by Django 2.0.2 on 2020-08-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200812_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
    ]
