# Generated by Django 2.0.2 on 2020-08-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200812_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='owner',
        ),
    ]
