# Generated by Django 2.0.2 on 2020-08-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200812_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
